ADMIN_MODE: "false"
BUFFERED_EVENTS: "true"
CLIENT_ADDRESS: "localhost:9090"
CLIENT_BACKUP_DIR: ""
CLIENT_EMAIL: ""
CLIENT_HOST: "localhost"
CLIENT_ID: ""
CLIENT_LOCAL_BACKUP: "false"
CLIENT_LOG_DIR: ""
CLIENT_NAME: ""
CLIENT_NEW_SERVICE: ""
CLIENT_PASSWORD: ""
CLIENT_PORT: 9090
CLIENT_PROFILE_PIC: ""
CLIENT_ROOT: ""
CLIENT_TESTING: ""
CLIENT_USERNAME: ""
EVENT_BUFFER_SIZE: 2
JWT_SECRET: ""
NEW_SERVICE: ""
SERVER_ADDR: "localhost:9191"
SERVER_ADMIN: "admin"
SERVER_ADMIN_KEY: ""
SERVER_HOST: "localhost"
SERVER_LOG_DIR: ""
SERVER_PORT: 9191
SERVER_TIMEOUT_IDLE: "900s"
SERVER_TIMEOUT_READ: "5s"
SERVER_TIMEOUT_WRITE: "10s"
SERVICE_ENV: ""
SERVICE_LOG_DIR: ""
SERVICE_ROOT: ""
SERVICE_TEST_ROOT: ""
